-- Computer generated by oopcodegen3.exe
-- Timestamp: 2023-12-25 21:23:07
do
	if WireMultiAgent ["WireMultiAgent:SystemDispatcher"]:GetStateStatus (SERVER) then
	
		WireMultiAgent ["WireMultiAgent:ProgramLogs"]:Constructor 			()
		WireMultiAgent ["WireMultiAgent:SignalProcessor"]:Constructor 		()
		WireMultiAgent ["WireMultiAgent:SignalProcessor"]:ReceiveCarriage 	()
		WireMultiAgent ["WireMultiAgent:PlayerSession"]:Constructor 		()
		WireMultiAgent ["WireMultiAgent:Submission"]:Constructor 			()
		WireMultiAgent ["WireMultiAgent:iSerializer"]:Constructor 			()
		WireMultiAgent ["WireMultiAgent:PerformIRTrace"]:Constructor 		()
		WireMultiAgent ["WireMultiAgent:PerformFingerprint"]:Constructor 	()
		
		WireMultiAgent ["WireMultiAgent:StylometryHelper"]:Constructor 		()
		WireMultiAgent ["WireMultiAgent:CodeRefactoring"]:Constructor 		()
		WireMultiAgent ["WireMultiAgent:HandlerProcess"]:Constructor 		()

		hook.Add ("InitPostEntity", "WireMultiAgent:InitEvent", function ()
			WireMultiAgent ["WireMultiAgent:Resources"]:PreConstructor 	 ()
			WireMultiAgent ["WireMultiAgent:Resources"]:Constructor 	 ()	
		end)

		hook.Add ("PlayerInitialSpawn", WireMultiAgent ["WireMultiAgent:PlayerSession"]:InternalId (), function (ply, _)
			WireMultiAgent ["WireMultiAgent:PlayerSession"]:CreatePlayerSession (ply)
		end)
		
		hook.Add ("PlayerDisconnected", WireMultiAgent ["WireMultiAgent:PlayerSession"]:InternalId (), function (ply)
			WireMultiAgent ["WireMultiAgent:PlayerSession"]:DestroyPlayerSession (ply)
		end)
	else
		WireMultiAgent ["WireMultiAgent:ClientHandler"]:Constructor ()
	end
end